<?php 
	print '
	<h1>O nama</h1>
	<h2>Mala priča o nama</h2>
	<video width="50%" controls poster="img/kratkifilm.jpg" >
	  <source src="video/kratkifilm.mp4" type="video/mp4">
	  Your browser does not support HTML5 video.
	</video>
	<p>Najstariji arheološki nalazi (dvije kamene sjekire, keramički materijal, oružje, nakit) potvrđuju postojanje života ljudi na ovom području od neolita (brončanog doba) preko željeznog do antike. U vrijeme rimske vlasti ovim područjem prolazi rimska «via magna» čiji su ostaci i danas ponegdje vidljivi. Čini se da se tada na području današnjeg Otrovanca nalazilo rimsko naselje lovia. Za samo područje Pitomače se ništa ne zna, mada je prona­đen veliki nalaz rimskog novca u da­našnjoj Dravskoj ulici. Staroslavensku kulturu (bjelobrdsku) 10. -12. st. potvrdila su po­kusna arheološka iskapanja.</p>
	<p>Naselje na tzv. Črljenoj Klisi smatrali su i Pitomačani i Otrovančani početkom svojih naselja. Dokazano je da se radi o nalazima od 10. do 18. st. te da je na tom mjestu bilo naselje Kopačevac koje se spominje i na popisu župa 1501. godine. Kop­ačevac je imao svoju župu i crkvu Sv. Helene ili Jelene. Naselje i crkvu su opustošili i srušili Turci u prvoj polovini 16. st. a crkva je ponovno ob­novljena 1684., no ne i naselje. Stanovnici Otrovanca su za svoje potrebe obnovili zidanu gotičku crkvu sv. Helene na Črljenoj Klisi oko 1700., ali već 1746. godine, kanonik vizitar piše da je crkva uslijed udara groma izgor­jela 1737. Nakon toga Otrovančani grade crkvu Sv. Helene u Otrovancu. Prvi poznati izvor koji spominje naselje Pythomezy (Pitomec, Pitomci- Pitomača) kao posjed bukovačkog vlastelinstva je faksimil doku­menta iz 1535. godine. Smatra se da je Pitomača u 15. i 16. stoljeću malo selo ili kmetsko selište bez kapele koje je pripadalo ili župi Sv. Helene u Kopačevcu ili župi svetog Petra i Pavla u tadašnjem Gereczu, današnji Stari Gradac. I nju su kao i ostala na­selja u okolini, oko 1540. srušili Turci, a obnavlja se kao novo naselje nakon protjerivanja Turaka iz Virovitice 1684. godine.Iako za godinu nastanka današnje Pitomače nema nikakvog pisanog do­kumenta smatra se da je to 1685. godi­na.</p>
	<p>Novo naselje formirano je na pro­storu današnje ulice J.J. Strossmavera tzv. Donji kraj. Već 1709. Pitomačani su sagradili drvenu crkvu Sv. Vida i 1710. traže da budu samostalna župa. Za ime naselja nema pisanih obra­zloženja iako neki autori tvrde da sva okolna naselja nose ime prema nekom obilježju pa je tako vjerojatno i sa Pitomačom; Sedlarica - zbog položaja između dva brežuljka, Črešnjevica - po trešnjama, črešnjama koje tu uspijeva­ju, Kladare - po stovarištu klada, Otrovanec - po starom bereku sa otrovnom vodom i biljem, a Pitomača - pitomina, korisna i obradiva zemlja. S godinama Pitomača je rasla do­seljavanjem novog stanovništva iz okolice Koprivnice, Križevaca i Đur­đevca, iz oslobođene Slavonije, Ugar­ske i Austrije što je vidljivo prema no­vim prezimenima u matičnim knjiga­ma iz 18. stoljeća. 1758. godine kada je osnovana đurđevačka pukovnija Vojne krajine, Pitomača je postala sjedište šeste sat­nije ili kumpanije. Kumpanija je obuh­vaćala 12 naselja u okolici: Veliku i Malu Črešnjevicu, Sesvete Podravske, Suhu Katalenu, Kloštar Podravski, Kozarevac, Sedlaricu, Grabrovnicu, Otrovanec, Dinjevac, Kladare i Pitomaču. Od tada se Pitomača počinje razvijati u poveće trgovište. Početkom 19. stoljeća Pitomača ima 1309 žitelja, a 1851. godine 2825 žitelja. No opći razvoj ipak su kočili brojni vojnički zakoni i stega. U sva­kom područnom selu kumpanije (sat­nije) nalazila se seoska straža ili štacija, a magazin za odlaganje viška uroda čini se da je bio na mjestu današnje drvne industrije Tvin-Gaj. Pitomački župnik Kovačić krajem 19. stoljeća o žiteljima Pitomače nakon dvjesto godina vojničke stege piše da su se razvile brojne negativnosti ali i dobre stvari koje su vidljive i danas, kao što su: red, čistoća, održavanje ulica i dvorišta, međusobna pomaganja i dr.</p>
	<p>Zahvaljujemo na videu <a href="http://www.arhiva.pitomaca.hr/index.php?option=com_content&view=category&layout=blog&id=145&Itemid=780" target="_blank">Općina Pitomača</a></p>';
?>